version: "2"
services:
  plone:
    #build: .
    image: interlegis/portalmodelo:3.0-12
    restart: always
    environment:
      ZEO_ADDRESS: zeoserver:8100
      ZEO_SHARED_BLOB_DIR: 'on'
    ports:
      - 8080:8080
      - 8881:8881
    depends_on:
     - zeoserver
    volumes:
     - data:/data

  zeoserver:
    #build: .
    image: interlegis/portalmodelo:3.0-12
    restart: always
    command: zeoserver
    environment:
      ZEO_SHARED_BLOB_DIR: 'on'
    volumes:
      - data:/data

volumes:
  data:
    driver: local
