version: "2"
services:
  plone:
    #build: .
    image: interlegis/portalmodelo:3.0
    environment:
      ZEO_ADDRESS: zeoserver:8100
    ports:
      - 8080:8080
    depends_on:
    - zeoserver

  zeoserver:
    image: plone/zeoserver:2.13.23
    volumes:
      - data:/data

volumes:
  data:
